server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://121.37.30.244:8761/eureka/
  instance:
    appname: eureka
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

